apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    {{- range $key, $value := .Values.deployment.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- range $key, $value := .Values.deployment.selectorLabels }}
      {{ $key }}: {{ $value }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- range $key, $value := .Values.deployment.selectorLabels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Values.deployment.container.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range .Values.deployment.container.ports }}
            - containerPort: {{ .containerPort }}
            {{- end }}
          env:
            {{- if .Values.deployment.container.env }}
            {{- toYaml .Values.deployment.container.env | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.deployment.container.resources | nindent 12 }}
