apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-calculator
  labels:
    app: web-calculator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web-calculator
  template:
    metadata:
      labels:
        app: web-calculator
    spec:
      containers:
        - name: {{ .Values.deployment.container.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          env: 
            {{- if .Values.deployment.container.env }}
            {{- toYaml .Values.deployment.container.env | nindent 12 }}
            {{- end }}
