apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Choose a port between 30000-32767, or remove this line to let Kubernetes assign one
