apiVersion: v1
kind: Service
metadata:
  name: web-calculator
spec:
  type: {{ .Values.service.type }}
  selector:
    app: web-calculator
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
