apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit
  labels:
    app: reddit
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: reddit
  template:
    metadata:
      labels:
        app: reddit
    spec:
      containers:
        - name: {{ .Values.deployment.container.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          env: 
            {{- if .Values.deployment.container.env }}
            {{- toYaml .Values.deployment.container.env | nindent 12 }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: "/"
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3

