image:
  repository: "raam2023/reddit"
  tag: "7"
  pullPolicy: Always

replicaCount: 2  # Adjust as per your scaling needs

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30001  # Ensure this port is open on the worker node

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: reddit.example.com  # Change this to your domain
      paths:
        - path: "/"
          pathType: ImplementationSpecific

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

nodeSelector: {}

tolerations: []

affinity: {}

deployment:
  enabled: true
  name: reddit
  labels:
    app: reddit
  selectorLabels:
    app: reddit
  replicas: 2
  container:
    name: reddit
    env: []
    readinessProbe:
      httpGet:
        path: "/"
        port: 3000
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "250m"
        memory: "256Mi"

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

